server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 生产环境数据库连接，默认连接本机 MySQL
    url: jdbc:mysql://localhost:3306/zhijian_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: zhijian_db
    # 请将在宝塔面板-数据库-root密码 中查看到的密码填在这里
    password: ${DB_PASSWORD:Lhnan0122..}
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      # 如果在宝塔 Redis 设置了密码，请填在这里；如果没有，留空即可
      password: ${REDIS_PASSWORD:}

# 生产环境日志级别
logging:
  level:
    root: INFO
    com.zhijian: INFO

knife4j:
  production: true # 生产环境是否开启文档，建议关闭

zhijian:
  ai:
    coze:
      api-token: ${COZE_API_TOKEN:sat_QgCl82pNnvtYPDHHTeBW2o5m0ZGqQmzjlyM7cDtIhV9CeT2bUZsK5Sq9GaFwlLqr}
      bot-id: 7592221151066325035
    openai:
      api-key: ${OPENAI_API_KEY:sk-a56903ddc505472a8a2c615250254bdc}
      base-url: https://api.deepseek.com
      
# Aliyun Config
aliyun:
  oss:
    endpoint: ${ALIYUN_OSS_ENDPOINT:oss-cn-shenzhen.aliyuncs.com}
    access-key-id: ${ALIYUN_OSS_ACCESS_KEY_ID:your_access_key_id}
    access-key-secret: ${ALIYUN_OSS_ACCESS_KEY_SECRET:your_access_key_secret}
    bucket-name: ${ALIYUN_OSS_BUCKET_NAME:liuhaonan-java-ai}
  sms:
    access-key-id: ${ALIYUN_SMS_ACCESS_KEY_ID:your_access_key_id}
    access-key-secret: ${ALIYUN_SMS_ACCESS_KEY_SECRET:your_access_key_secret}
    sign-name: ${ALIYUN_SMS_SIGN_NAME:阿里云短信测试}
    template-code: ${ALIYUN_SMS_TEMPLATE_CODE:SMS_329195922}
